"""
Composite tools generated by the Unity MCP visual tool builder
(Window -> Unity MCP -> Tool Builder), appended below by that window's
"Generate" button. Nothing in this file is hand-maintained except this header
— feel free to edit generated functions directly, the builder never rewrites
what's already here, it only ever appends.

Each generated function is a normal @workflow-decorated composite tool exactly
like the built-in ones in workflows.py (batch_execute, create_behavior_tree,
...) — see that file for the pattern this one follows.
"""
from .workflows import workflow  # noqa: F401  (imported for generated functions below to use)
