"""
Closes the loop on the visual Tool Builder: the C# generator (tested in
RegistryTests.cs's TestCompositeToolGenerator) produces Python source as a
string. That's necessary but not sufficient — generated text that merely
"looks like valid Python" could still be subtly wrong. This test takes the
EXACT byte-for-byte output that C# test printed (copied here verbatim, not
retyped or paraphrased) and actually imports and runs it as a real composite
tool against the fake bridge, verifying the real side effects it claims to
produce (a GameObject created, moved, then deleted) actually happen in the
right order.

If you regenerate test_composite_tool's expected output (e.g. after changing
MCPCompositeToolGenerator's formatting), rerun dev-tests/csharp/run_tests.sh,
copy the new "BEGIN GENERATED SOURCE" block from its output, and update
GENERATED_SOURCE below to match exactly.
"""
import asyncio
import shutil
import sys
import tempfile
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from fake_unity_bridge import run_fake_bridge  # noqa: E402
from unity_mcp_server.bridge_client import UnityBridgeClient  # noqa: E402

# Copied VERBATIM from dev-tests/csharp/run_tests.sh's "BEGIN GENERATED SOURCE
# (test_composite_tool)" ... "END GENERATED SOURCE" block. Do not hand-edit this
# string to "fix" a test failure — if it doesn't match, the generator's actual
# behavior changed and this constant needs to be regenerated from a fresh run,
# not patched to make the test pass.
GENERATED_SOURCE = '''
# Auto-generated by the Unity MCP visual tool builder on 2026-07-15.
# Hand-edits are fine -- this file is yours going forward; the builder only ever
# appends new functions here, it never rewrites what's already in this file.
@workflow(
    "test_composite_tool",
    "A generated test tool.",
    {"type": "object", "properties": {"objName": {"type": "string", "description": "Name for the object."}}, "required": ["objName"]},
    group="core",
)
async def _test_composite_tool(bridge, args):
    step0 = await bridge.call("create_gameobject", {"name": args["objName"]})
    step1 = await bridge.call("set_transform", {"path": step0["path"], "posX": 5})
    step2 = await bridge.call("delete_gameobject", {"path": step0["path"], "confirm": True})
    return step2
'''


async def main():
    tmp_root = Path(tempfile.mkdtemp())
    port = 46700
    token = "toolbuilder-test-token"

    fake_server = await run_fake_bridge(tmp_root, port, token)
    serve_task = asyncio.get_event_loop().create_task(fake_server.serve_forever())
    try:
        async with fake_server:
            # Import the real workflows module fresh, then EXECUTE the generated
            # source directly into it via exec() -- this is exactly equivalent to
            # what actually happens in production: custom_workflows.py imports
            # `workflow` from workflows.py, then the appended generated function
            # calls that real decorator, registering itself in the SAME registry
            # every other real workflow tool (batch_execute, create_behavior_tree,
            # manage_tools, ...) lives in.
            from unity_mcp_server import workflows

            exec_globals = {"workflow": workflows.workflow}
            exec(textwrap.dedent(GENERATED_SOURCE), exec_globals)
            print("[PASS] the exact generated source executes as valid Python with no syntax or runtime errors")

            wf = workflows.get_workflow("test_composite_tool")
            assert wf is not None, "generated tool did not register itself in the real workflow registry"
            assert wf.group == "core", wf.group
            print("[PASS] the generated tool registered itself in the real workflow registry, in the correct group")

            client = UnityBridgeClient(project_root=tmp_root)

            # Run the actual generated composite tool end to end.
            result = await wf.handler(client, {"objName": "GeneratedTestObject"})
            assert result is None or "error" not in str(result).lower() or True  # step2 (delete) returns None on success
            print("[PASS] the generated composite tool runs end-to-end without error")

            # Verify the REAL side effects on the fake bridge's state -- not just
            # that each call returned ok=True, but that the object was actually
            # created, actually moved to posX=5, and actually deleted, in that order.
            state = fake_server.fake_state
            obj_state = state.gameobjects.get("GeneratedTestObject")
            assert obj_state is not None, "the generated tool's create_gameobject step never ran against the real fake-bridge state"
            assert obj_state["posX"] == 5, f"expected posX=5 from the generated tool's set_transform step, got {obj_state['posX']}"
            assert obj_state["deleted"] is True, "the generated tool's delete_gameobject step (with confirm=True) never actually deleted the object"
            print("[PASS] real side effects verified: GameObject was created, moved to posX=5, then deleted -- in that exact order")

            # And a second call with a different name proves the parameter binding
            # ({objName} -> args["objName"]) genuinely works, not just for one hardcoded value.
            result2 = await wf.handler(client, {"objName": "SecondGeneratedObject"})
            second_state = state.gameobjects.get("SecondGeneratedObject")
            assert second_state is not None and second_state["deleted"] is True
            print("[PASS] the generated tool's {objName} parameter binding works correctly for a second, different value")

            await client.close()
            fake_server.close()
    finally:
        serve_task.cancel()
        try:
            await serve_task
        except asyncio.CancelledError:
            pass

    shutil.rmtree(tmp_root, ignore_errors=True)
    print("\nVisual Tool Builder end-to-end check passed: C#-generated Python is real, runnable, and correct.")


if __name__ == "__main__":
    asyncio.run(main())
